import FaqItem from "../components/FaqItem";

export default function Faqs() {
    return (
        <div id="faqs" className="section py-8 sm:py-16 flex flex-col items-center bg-black space-y-10 px-10">
            <div className="text-2xl sm:text-5xl text-green font-black">FAQS</div>
            <FaqItem title='When was Bull Solana founded?' content={<div>Bull was founded early 2022 with the aim of building the meme ecosystem’s most favorite meme coin through a system that helps users get easy access to the crypto world. In the long run, we will be building easy-to-understand services that anyone (crypto experts/novice) can use to trade tokens and NFTs on Solana, learn about the blockchain industry, and DeFi, while avoiding dangerous schemes within the space.<br></br> Though $BULL will be launched as a meme coin, the team is focused on building a community token where meme meets utility such as governance and P2E games.</div>}></FaqItem>
            <FaqItem title='What differentiate us from the others?' content={<div>We imploy the technological advantages of the solana blockchain to create an eco-friendly and efficient token whose value is locked in on the community participation rather than individuals or a group of people.<br></br><br></br>Bull is coined after the cryptospace terminology “Bullish season” as we believe and will continue to work towards an ever green candle without taking shortcuts. We believe to grow over the time without compromising transparency, meme culture, and without involving in disingenious practices.</div>}></FaqItem>
            <FaqItem title='Why solana blockchain?' content={<div>Powerful for developers. Fast for everyone.<br></br><br></br>Solana is the fastest blockchain in the world and the fastest growing ecosystem in crypto, with thousands of projects spanning DeFi, NFTs, Web3 and more.</div>}></FaqItem>
            <FaqItem title='What  is the BULL’s future development plan?' content={<div>We imploy the technological advantages of the solana blockchain to create an eco-friendly and efficient token whose value is locked in on the community participation rather than individuals or a group of people.<br></br><br></br>Bull is coined after the cryptospace terminology “Bullish season” as we believe and will continue to work towards an ever green candle without taking shortcuts. We believe to grow over the time without compromising transparency, meme culture, and without involving in disingenious practices.</div>}></FaqItem>
            <FaqItem title='Mission and vision?' content={<div><span className="text-green">Vision:</span> We aim to become a Solana ambasador for positive news and also serve as a bull eye, watching over every other token and NFTs in the blockchain.<br></br><br></br><span className="text-green">Mission:</span> Our mission is to build a cooperative community and social token on the Solana blockchain. We’re building a system that helps users get easy access to the crypto world.<br></br>In the long run, we will be building easy-to-understand services that anyone (crypto experts/novice) can use to trade tokens and NFTs on Solana, learn about the blockchain industry, and DeFi, while avoiding dangerous schemes within the space.</div>}></FaqItem>
        </div>
    )
}